-- Zweite Befüllungsrunde der Wissens-Basis (coach_wissen, 0046) — diesmal aus
-- drei neuen, von der Nutzerin bereitgestellten Dokumenten: AKA ADHS-Lexikon
-- v2 (110+ Begriffe A-Z), AKA-Dokumentenset-Übersicht (reine Navigation,
-- nichts draus übernommen) und AKA Coaching-Programm-Handbuch v3 (deutlich
-- vertiefte Neufassung des Ursprungsdokuments aus 0047: jedes Modul hat
-- jetzt einen "Mechanismen dahinter"-Abschnitt + echte Klienten-FAQ, und es
-- gibt zwei komplett neue Module: Morgenroutine (9) und Abendroutine (10)).
--
-- Kuratierungslogik (Nutzerin-Vorgabe: "je nach Möglichkeit und Umfang
-- bewerten/sortieren"): bestehende 8 Modul-Einträge aus 0047 bleiben
-- unverändert stehen, hier kommt je Modul ein ZWEITER, schlanker Eintrag
-- "Vertiefung & Klienten-FAQ" dazu (Mechanismus-Hintergrund + die
-- griffigsten neuen Zusatzfragen) statt die bestehenden Einträge zu
-- ersetzen. Bewusst NICHT übernommen (gleiche Logik wie 0047): Teil 9
-- Prüfungsfragen (Selbsttest der Nutzerin, keine Gesprächsgrundlage für
-- Aka), das Quellenverzeichnis (rohe URL-Liste), Teil 6-8
-- Minute-für-Minute-Sitzungsleitfäden (das ist ein eigenes, größeres
-- Struktur-Thema für einen künftigen "geführten Sitzungs-Modus", kein
-- Wissenstext — siehe Übergabeprotokoll) und ca. 90 der 110
-- Lexikon-Begriffe (nur die für ein laufendes Gespräch wirklich nützliche
-- Teilmenge wurde übernommen, alles andere ist entweder schon in den
-- Modul-Einträgen enthalten oder reines Prüfungs-/Fachpersonen-Wissen ohne
-- Gesprächsrelevanz für Aka).

insert into public.coach_wissen (bereich, titel, text) values

-- Zwei komplett neue Module aus Handbuch v3 (bisher nicht in coach_wissen
-- vorhanden UND bisher kein eigener bereich-Wert) — siehe dazu auch die
-- gleichzeitige Code-Änderung, die erstmals einen Aka-Chat mit
-- bereich="morgenroutine"/"abendroutine" in RoutineTabView.jsx einbaut.
('morgenroutine', 'Morgenroutine-Modul: Wissenschaft, Gespräch, Experimente', $$Hintergrund: Die Morgenroutine ist keine eigenständige neue Baustelle, sondern die Klammer, in der Hydration, Tageslicht, Medikamente, Ernährung und Gewohnheiten in den ersten 30-60 Minuten des Tages praktisch zusammenlaufen. Der Morgen ist zugleich das vulnerabelste Zeitfenster: "Sleep Inertia" (Schlaftrunkenheit) reduziert Reaktionszeit, Entscheidungsfähigkeit und Arbeitsgedächtnis 15-30 (teils bis 60) Minuten nach dem Aufwachen messbar — bei ADHS trifft das genau die Fähigkeiten, die für einen guten Start gebraucht würden. Jede morgendliche Entscheidung (was anziehen, was essen, was zuerst) verbraucht knappe exekutive Ressourcen ("Decision Fatigue") — eine im Voraus festgelegte Reihenfolge eliminiert diese Last, man muss nur noch ausführen, nicht mehr entscheiden. Die Cortisol Awakening Response (natürlicher Kortisolanstieg in den ersten 30-45 Min. nach dem Aufwachen) wird durch Licht mitbeeinstellt — ein weiterer Grund für "möglichst bald ans Licht". Snoozen fragmentiert die letzte Schlafphase in unvollständige Zyklen und verstärkt die Schlaftrunkenheit, statt zu erholen — ein klassisches Belohnungsaufschub-Muster (5 Min. mehr fühlen sich gut an), keine Charakterschwäche. Kernprinzip: die erste Handlung nach dem Aufwachen so klein wie möglich halten (Wasser trinken, ans Fenster stehen) — jeder kleine Erfolg erhöht über einen Selbstwirksamkeitsschub die Wahrscheinlichkeit für den nächsten Schritt (Chaining). Häufiger Coaching-Fehler: zu viele neue Verhaltensweisen auf einmal einbauen — wirksamer ist zuerst eine feste REIHENFOLGE für längst vorhandene Handlungen, danach schrittweise erweitern.

Erklärung für Gespräche (60 Sek.): "Die ersten Minuten nach dem Aufwachen sind bei ADHS die schwierigsten — dein Gehirn ist noch nicht richtig online, und jede Entscheidung kostet extra Kraft. Eine feste Morgenroutine nimmt dir diese Entscheidungen ab: du musst nicht mehr überlegen, was als Nächstes kommt, du machst es einfach, weil es immer in derselben Reihenfolge passiert. Wichtig: klein anfangen, nicht fünf neue Gewohnheiten auf einmal, sondern eine feste Kette aus 3-4 Schritten, die du schon machst — nur eben immer in derselben Reihenfolge."

Typische Probleme: "Ich brauche ewig, um aus dem Bett zu kommen" (Sleep Inertia, fehlender erster Trigger), "Jeder Morgen sieht anders aus, ich improvisiere" (fehlende Kette), "Ich schaue als Erstes aufs Handy" (stärkster verfügbarer Reiz gewinnt automatisch gegen jede Struktur), "An guten Tagen klappt's, an schlechten komplett nicht" (kein Notfall-Minimum für schwere Tage).

Coaching-Fragen: "Was ist aktuell der allererste Handgriff nach dem Aufwachen?" / "Welche drei Dinge machst du sowieso jeden Morgen, unabhängig von Motivation?" / "In welcher Reihenfolge könnten die ablaufen?" / "Was wäre dein Notfall-Minimum an einem richtig schlechten Tag?" / "Wo könntest du Dinge hinlegen, damit der nächste Schritt automatisch sichtbar ist?"

Experimente: Tiny — eine Wenn-Dann-Regel für den allerersten Moment ("Wenn der Wecker klingelt, setze ich mich sofort aufrecht hin"), 7 Tage, nichts weiter. Standard — 3-Schritte-Kette festlegen (z.B. Wasser, 2 Min. ans Fenster, Medikament/Frühstück), Handy bleibt bis danach außer Reichweite, Ja/Nein-Tracking pro Schritt. Advanced — vollständige Kette mit 5-6 Schritten inkl. fester "Notfall-Version" für schlechte Tage, Handy erst nach Abschluss der Kette.

Rot-Flags → Fachperson: massive morgendliche Antriebslosigkeit über Wochen (über "schwerer Start" hinaus) → Arzt/Psychotherapeut (Ausschluss Depression), extreme Schlaftrunkenheit mit Verwirrtheit über Minuten hinaus → Arzt, panikartige morgendliche Überforderung/Angstsymptome → Psychotherapeut. Eine bestimmte Aufwachzeit nie als "richtig" vorschreiben — Reihenfolge ist wichtiger als Uhrzeit.

Häufige Zusatzfragen: "Ich bin extremer Nachtmensch, ist eine Morgenroutine realistisch?" → Ja, Ziel ist eine feste KURZE Abfolge direkt nach dem individuellen Aufwachzeitpunkt, nicht "früh aufstehen" — die Uhrzeit ist zweitrangig, schrittweise Vorverlagerung über Wochen ist realistischer als ein abrupter Wechsel. "Meine Routine klappt allein, aber sobald Kinder/Partner mitreden bricht sie zusammen" → unveränderlichen Kern auf 1-2 wirklich unverhandelbare Schritte reduzieren (z.B. "Wasser trinken" geht fast immer), statt eine lange Kette anzustreben.$$),

('abendroutine', 'Abendroutine-Modul: Wissenschaft, Gespräch, Experimente', $$Hintergrund: Wie die Morgenroutine ist die Abendroutine eine Klammer-Funktion — sie verbindet Schlaf, Tageslicht/Blaulicht, Medikamenten-Rebound und Gewohnheiten im letzten Zeitfenster des Tages, hat aber eine doppelte Aufgabe: den Tag bewusst abschließen UND den Schlaf physiologisch vorbereiten. Der Abend hat anders als der Morgen keine externe Taktung (keine feste Deadline wie Arbeitsbeginn) — die Abendroutine muss diese Struktur künstlich nachbilden. "Revenge Bedtime Procrastination" (bewusstes Hinauszögern des Schlafengehens trotz Müdigkeit, um sich "Zeit für sich" zurückzuholen) ist bei ADHS besonders ausgeprägt, weil der Tag oft als fremdbestimmt erlebt wird — Lösung ist NICHT, das Bedürfnis zu bekämpfen, sondern "Ich-Zeit" bewusst VOR dem Runterfahren einzuplanen statt sie gegen den Schlaf zu erkämpfen. In den 60-90 Min. vor dem Einschlafen sinkt normalerweise die Körperkerntemperatur, parasympathische Aktivität nimmt zu ("Wind-Down") — helles Licht, fordernde Bildschirminhalte, intensive Bewegung und Koffein wirken dem entgegen. Bildschirme wirken über zwei Kanäle gegen guten Schlaf: den Licht-/Melatonin-Effekt UND einen kognitiv-emotionalen Aktivierungseffekt durch die Inhalte selbst (Autoplay-Sog, soziale Vergleiche) — bei ADHS oft stärker als der reine Lichteffekt, weil neuartige, schnell wechselnde Reize das Belohnungssystem besonders stark ansprechen. Der Medikamenten-Rebound (Nachlassen der Stimulanzien-Wirkung) fällt häufig genau in den frühen Abend — in dieser Phase lieber "sanfter" gestalten statt anspruchsvolle Aufgaben einzuplanen. Unerledigte "Open Loops" im Kopf sind ein bekannter Auslöser für nächtliches Grübeln — ein kurzer "Brain Dump" (To-do-Liste für morgen in 2 Min. aufschreiben) externalisiert diese offenen Punkte. Wie am Morgen gilt: 2-3 feste, stabile Schritte sind wirksamer als eine "perfekte", aber unrealistische 8-Schritte-Kette.

Erklärung für Gespräche (60 Sek.): "Der Abend hat anders als der Morgen keine natürliche Struktur von außen, deshalb zieht sich Bildschirmzeit oder Aufschub oft endlos hin. Eine Abendroutine gibt dir diese fehlende Struktur künstlich zurück — sie signalisiert deinem Körper 'jetzt wird es Nacht' und erlaubt deinem Kopf, den Tag abzuschließen, statt mit offenen To-dos ins Bett zu gehen. Wenn du das Gefühl hast, dir 'deine Zeit zurückholen' zu müssen, indem du nachts wach bleibst — das ist ein bekanntes ADHS-Muster. Die Lösung ist nicht, dagegen anzukämpfen, sondern dir diese Zeit bewusst VOR dem Runterfahren einzuplanen."

Typische Probleme: "Ich weiß, ich sollte schlafen, aber ich will noch was für mich haben" (Revenge Bedtime Procrastination), "Sobald ich mit Scrollen/einer Serie anfange, verliere ich das Zeitgefühl" (Hyperfokus + Autoplay), "Ich liege im Bett und mein Kopf macht To-do-Listen" (Open Loops), "Abends bin ich gereizt, ohne zu wissen warum" (möglicher Rebound-Zeitpunkt).

Coaching-Fragen: "Woran merkst du, dass ein Tag für dich vorbei ist?" / "Fühlst du dich abends manchmal so, als müsstest du dir deine Zeit zurückholen? Wann genau?" / "Gehen dir abends im Bett Dinge durch den Kopf, die du noch erledigen musst?" / "Was wären die zwei, drei wichtigsten Schritte für eine Abendroutine — nicht acht, nur zwei oder drei?"

Experimente: Tiny — eine Wenn-Dann-Regel ("Wenn ich ins Bett gehe, lege ich das Handy außerhalb der Armreichweite"), 7 Tage. Standard — 2-Schritte-Kette 30 Min. vor Ziel-Schlafenszeit (Brain Dump + Bildschirm weg/Licht dimmen), Ja/Nein-Tracking. Advanced — bewusst eingeplante "Ich-Zeit" VOR dem Wind-Down-Fenster + feste 30-45-min. Runterfahr-Kette danach.

Rot-Flags → Fachperson: anhaltende, quälende nächtliche Grübelschleifen mit Angstcharakter → Psychotherapeut, abendliche Stimmungseinbrüche mit Verdacht auf mehr als "Rebound" → Arzt/Psychotherapeut, suchtartiges nächtliches Bildschirmverhalten mit Leidensdruck → Psychotherapeut, nächtliche Unruhe mit körperlichen Symptomen (Herzrasen, Atemnot) → Arzt.

Häufige Zusatzfragen: "Ich bin abends zu erschöpft für eine Routine, reicht nicht einfach ins Bett fallen?" → Genau in dieser Erschöpfung liegt oft die Ursache für schlechten Schlaf (kein Wind-Down, Gedankenkarussell) — Lösung ist keine aufwändige Routine, sondern eine extrem kleine (nur "Licht dimmen + Handy weg"). "Ich habe abends oft noch Energie, weil das Medikament nachlässt und ich aufdrehe" → möglicher Rebound — Abendroutine bewusst NACH diesem Fenster beginnen, die Energie vorher in eine "erlaubte Ich-Zeit" kanalisieren statt dagegen anzukämpfen.$$),

-- Vertiefungen zu den 8 bestehenden Modulen (0047) — ergänzt, ersetzt nichts.
('schlaf', 'Schlaf-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Schlaf wird durch zwei Prozesse gesteuert (Zwei-Prozess-Modell nach Borbély): Prozess S (Schlafdruck, baut sich über den Tag auf) und Prozess C (zirkadianer Rhythmus). Bei ADHS ist meist nicht der Schlafdruck das Problem, sondern die Phasenlage von Prozess C — wenn jemand sagt "Ich bin todmüde, kann aber nicht einschlafen", ist das kein Widerspruch, sondern typisch für eine verzögerte zirkadiane Phase. Die richtige Frage ist dann nicht "Warum gehst du nicht früher ins Bett", sondern "Wann fängt dein Körper überhaupt an, müde zu werden — unabhängig von der Uhrzeit." Melatonin ist entgegen einem verbreiteten Missverständnis kein Beruhigungsmittel, sondern primär ein Zeitgeber-Signal — falsches Timing kann die Phase sogar in die falsche Richtung verschieben, daher rein ärztliches Terrain. Schlafeffizienz (tatsächliche Schlafzeit ÷ Zeit im Bett) hilft zu unterscheiden: 9 Std. im Bett, aber nur 6 Std. Schlaf ist ein anderes Problem (Einschlaf-/Durchschlafstörung) als schlicht zu wenig Zeit im Bett.

Häufige Zusatzfragen: "Hilft ein Mittagsschlaf, wenn ich nachts zu wenig schlafe?" → Kurz (10-20 Min., vor 15 Uhr) kann er kurzfristig helfen, ohne die Nacht zu stören; länger/später kann er den abendlichen Schlafdruck reduzieren und das Einschlafen erschweren. "Ich schlafe am Wochenende bis mittags, ist das schlimm?" → Das ist "Social Jetlag", eine Art selbstgemachter Zeitzonenwechsel, der montags wie ein kleiner Jetlag wirkt — ein Unterschied von max. ca. 1 Std. zwischen Wochentag/Wochenende ist realistischer als "gar keiner". "Soll ich das Bett nur zum Schlafen benutzen?" → Anerkanntes Prinzip aus der Schlafverhaltenstherapie (Stimuluskontrolle: "Bett = Schlaf" statt "Bett = Scrollen/Grübeln"), darfst du als Experiment vorschlagen, eine strukturierte Insomnie-Behandlung (KVT-I) bleibt aber therapeutisches Terrain.$$),

('hydration', 'Hydration-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Koffein blockiert Adenosin-Rezeptoren (Adenosin ist das über den Tag ansteigende "Müdigkeitssignal") und erhöht indirekt dopaminerge/noradrenerge Aktivität — erklärt, warum viele mit ADHS Kaffee als funktionale Selbstmedikation beschreiben, ein nachvollziehbarer, nicht pathologischer Mechanismus. Individuelle genetische Unterschiede im Koffeinabbau (u.a. Enzym CYP1A2) erklären, warum ein Nachmittagskaffee bei manchen unproblematisch, bei anderen schlafzerstörend ist — individuelles Ausprobieren ist wirksamer als pauschale Cut-off-Regeln. Trinken wird besonders leicht vergessen, weil Durst erst spät bewusst wahrgenommen wird und keine externe Deadline existiert — macht Hydration zu einem guten Einstiegsmodul, weil Erfolg schnell spürbar und wenig aufwändig ist.

Häufige Zusatzfragen: "Kann man zu viel trinken?" → In seltenen Fällen ja (Hyponatriämie durch exzessive Mengen weit über normalem Bedarf) — für den Alltag kein realistisches Thema, außer bei zwanghaftem Trinkverhalten (dann Arztthema). "Zählt Kaffee/Tee zur Trinkmenge?" → Ja, der alte "Kaffee entwässert netto"-Mythos ist widerlegt, bei gewohnheitsmäßigem Konsum trägt er zur Flüssigkeitsbilanz bei — das eigentliche Thema ist Timing, nicht Menge. "Sind Energy-Drinks eine Alternative zu Kaffee?" → Kombinieren oft hohe Koffeinmengen mit Zucker/weiteren Stimulanzien, Gesamtwirkung schwerer einzuschätzen — bei Stimulanzien-Medikation ausdrücklich mit Arzt/Apotheker besprechen, keine Coaching-Empfehlung.$$),

('tageslicht', 'Tageslicht-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Entscheidend ist nicht nur DASS Licht auf die Augen trifft, sondern WANN — Licht in der ersten Tageshälfte verschiebt die innere Uhr nach vorne (früher), Licht spätabends nach hinten (später), die sogenannte Phasenantwortkurve. Das erklärt, warum gezieltes Morgenlicht wirksamer ist als "irgendwann tagsüber draußen sein". Zur Einordnung: Innenraumlicht ca. 100-500 Lux, bewölkter Tag draußen 1.000-10.000 Lux, sonniger Tag draußen bis 100.000 Lux, Tageslichtlampen meist 10.000 Lux bei 20-30cm Abstand — "am Fenster stehen" ist deutlich schwächer als "draußen sein", weil Fensterglas viel wirksames Licht filtert. Ein 10-15-minütiger Spaziergang morgens ist oft wirksamer als 30 Min. am Fenster drinnen. Morgenlicht ist additives Verhalten (etwas Neues tun), Abendlicht-Reduktion ist Verzichtsverhalten (Bildschirm weglassen) — bei ADHS wegen reward-getriebener Impulskontrolle besonders schwer, deshalb in der Praxis zuerst am Morgenlicht arbeiten (leichter, schneller Erfolg), erst danach an der Abendlicht-Reduktion.

Häufige Zusatzfragen: "Wirkt eine Tageslichtlampe auch durchs Fenster/nebenbei beim Arbeiten?" → Nebenbei laufende Nutzung (Lampe seitlich am Schreibtisch) ist möglich, ein Blick durchs geschlossene Fenster nach draußen ersetzt sie aber nicht in der Intensität. "Ich bin im Homeoffice und komme tagelang kaum raus" → Sehr häufiges, reales Problem — ohne den "erzwungenen" Lichtkontakt durch einen Arbeitsweg lohnt sich ein bewusst eingebauter Ersatz-Trigger (kurzer Spaziergang als "Pendel-Ersatz" zu Arbeitsbeginn). "Hilft ein Solarium wie Lichttherapie?" → Nein, Solarien sind auf UV-Strahlung (Bräunung) ausgelegt, nicht auf die für die innere Uhr relevante sichtbare Lichtintensität, und bergen eigene Gesundheitsrisiken.$$),

('ernaehrung', 'Ernährung-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Nach einer kohlenhydratreichen, ballaststoff-/proteinarmen Mahlzeit steigt der Blutzucker rasch, was eine hohe Insulinausschüttung auslöst, die den Blutzucker danach unter das Ausgangsniveau drücken kann (reaktive Hypoglykämie) — die Symptome (Konzentrationsabfall, Reizbarkeit, Zittrigkeit) überschneiden sich stark mit ADHS-Symptomen, ein Nachmittagstief ist also nicht automatisch "die ADHS", sondern oft schlicht die Mahlzeitenstruktur des Vormittags. Protein/Fett/Ballaststoffe verlangsamen die Magenentleerung und erzeugen eine flachere, länger anhaltende Blutzuckerkurve — die physiologische Basis für "nicht Kohlenhydrate weglassen, sondern kombinieren". Hyperfokus unterdrückt interozeptive Signale (Hunger, Durst) zugunsten der fokussierten Aufgabe — "vergiss zu essen" ist kein Willensproblem, sondern ein Aufmerksamkeitsphänomen; externe, zeitbasierte Trigger (feste Essenszeiten, Alarm) sind wirksamer als "auf den Körper hören".

Häufige Zusatzfragen: "Ist Intervallfasten gut oder schlecht bei ADHS?" → Keine spezifische Empfehlung — Fasten-Phasen können bei ohnehin unregelmäßigem Essverhalten das Risiko für Konzentrationseinbrüche erhöhen, besonders mit Stimulanzien (appetithemmend); individuell beobachten, bei bestehenden Essproblemen an Arzt/Ernährungstherapie verweisen. "Macht Alkohol die Symptome schlimmer?" → Wirkt kurzfristig dämpfend, stört aber Schlaf/Dehydratation und verschlechtert dadurch am Folgetag Konzentration/Stimmung — den Mechanismus darfst du erklären, Trinkmengen bleiben ärztliches Thema. "Sollte ich Kohlenhydrate ganz weglassen?" → Nein, widerspricht dem Kombinations-Prinzip und erhöht eher das Heißhunger-Risiko.$$),

('training', 'Training-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Bewegung erhöht akut die synaptische Verfügbarkeit von Dopamin/Noradrenalin, chronisches Training zusätzlich Wachstumsfaktoren wie BDNF (neuronale Plastizität) — zwei Zeitfenster: akuter Effekt (Minuten bis Stunden nach einer Einheit, eignet sich als "Werkzeug" statt nur als abstraktes Gesundheitsziel) und chronischer Effekt (Wochen bis Monate). Closed-Skill-Bewegungen (Schwimmen, Yoga, stabile Umgebung) wirken eher beruhigend/regulierend auf Hyperaktivität, Open-Skill-Bewegungen (Mannschaftssport, ständige Reaktion auf wechselnde Umgebung) beanspruchen zusätzlich exekutive Funktionen und zeigen tendenziell stärkere Aufmerksamkeitseffekte — Faustregel: starke innere Unruhe profitiert oft zuerst von Closed-Skill, reine Aufmerksamkeitsprobleme eher von Open-Skill. Die Forschungslage zur Wirksamkeit ist robust, das eigentliche Praxisproblem ist Adhärenz: Startschwierigkeiten sind ein Kernsymptom exekutiver Dysfunktion, keine mangelnde Motivation im umgangssprachlichen Sinn.

Häufige Zusatzfragen: "Ich habe Angst, dass ich mit Training genauso wenig durchhalte wie mit allem anderen" → Typisches, ADHS-bedingtes Muster (Neuheitsbedarf, Belohnungsaufschub-Schwierigkeiten, All-or-Nothing-Denken), kein individuelles Versagen — deshalb bewusst klein und variantenreich starten, nicht "mehr Disziplin". "Welche Sportart ist am besten für ADHS?" → Keine "beste" Sportart, aber Closed-Skill eher beruhigend, Open-Skill eher aufmerksamkeitsfördernd (siehe Vertiefung) — die tatsächlich durchgehaltene Sportart ist wichtiger als die theoretisch optimale. "Kann ich Sport statt Medikamente nehmen?" → Nein, Bewegung ist eine sinnvolle Ergänzung mit eigenständigem, aber begrenztem Effekt, kein Ersatz für medizinisch indizierte Behandlung — diese Entscheidung liegt ausschließlich beim Arzt.$$),

('gewohnheiten', 'Gewohnheiten-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Barkleys Modell beschreibt ADHS im Kern als Störung der Verhaltenshemmung, die fünf nachgeordnete exekutive Funktionen beeinträchtigt: Arbeitsgedächtnis, Selbstregulation von Affekt/Motivation, Internalisierung von Sprache (inneres Selbstgespräch), Rekonstitution/Problemlöse-Kreativität, motorische Verhaltenskontrolle — wenn eine Routine nicht klappt, lohnt sich die Frage, an welcher dieser Stellen es hakt. Implementation Intentions verlagern die Handlungsauslösung von bewusster Entscheidung hin zu einer quasi-automatisierten Reiz-Reaktions-Verbindung, besonders wirksam bei ADHS, weil die bewusste Erinnerungsleistung ohnehin limitiert ist. Beim Habit-Loop-Modell (Cue-Routine-Reward) ist bei ADHS besonders die Belohnungskomponente kritisch: Da das Dopaminsystem auf verzögerte, kleine Belohnungen schwächer reagiert, verpuffen langfristige, abstrakte Belohnungen wirkungslos — unmittelbare, spürbare Mini-Belohnungen (Häkchen, Streak) sind wirksamer, ein zentrales Argument für Tracking-Feedback in der App.

Häufige Zusatzfragen: "Wie lange dauert es, bis eine Gewohnheit automatisch ist?" → Die "21 Tage"-Zahl ist ein Mythos, Forschung zeigt eine sehr große Spannbreite (Wochen bis über zwei Monate) — Erfolg nicht an einer festen Tageszahl festmachen, sondern daran, wie oft die Handlung ohne bewusste Anstrengung passiert. "Ich falle nach Urlaub/Krankheit komplett aus der Routine" → Erwartbares Muster bei verändertem Kontext, kein Rückschritt — ein fester "Wiedereinstiegs-Trigger" (erster Tag zurück = Minimalversion) hilft mehr als komplett neu anzufangen. "Sind Apps/Reminder nicht selbst wieder eine Sache, die ich vergesse zu bedienen?" → Berechtigter Einwand, deshalb funktionieren passive, push-basierte Erinnerungen (die App meldet sich von selbst) besser als aktive Systeme, die man selbst öffnen müsste.$$),

('supplemente', 'Supplemente-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Niedrigere Mikronährstoff-Spiegel bei ADHS in Gruppenstudien sind eine Assoziation auf Gruppenebene — sie sagt nichts darüber aus, ob eine einzelne Person einen Mangel hat, ob dieser Ursache oder Folge unregelmäßiger Ernährung ist, und ob ein Ausgleich die Symptomatik verbessern würde. Diese Unterscheidung (Assoziation vs. Kausalität, Gruppe vs. Individuum) ist der wichtigste Baustein für seriöse Information ohne falsche Hoffnungen. Eisen ist Kofaktor der Tyrosinhydroxylase (geschwindigkeitsbestimmender Schritt der Dopamin-Synthese) — Eisensubstitution ohne nachgewiesenen Mangel ist aber nicht harmlos: Eisenüberladung ist toxisch, deshalb ist Selbstsupplementierung ohne Blutbild ein klares Red-Flag-Thema. Viele frei verkäufliche Supplemente können mit ADHS-Medikation interagieren — die wichtigste Coach-Funktion ist, überhaupt sichtbar zu machen, WAS jemand alles gleichzeitig einnimmt, und diese Liste dem Arzt/Apotheker vorzulegen.

Häufige Zusatzfragen: "Ich nehme ein Multivitaminpräparat auf Verdacht, ist das schädlich?" → In normaler Dosierung meist unbedenklich, aber ohne nachgewiesenen Mangel auch ohne belegten ADHS-Nutzen; fettlösliche Vitamine (A, D, E, K) können sich bei Daueranwendung anreichern — grundsätzlich ärztlich besprechen statt "auf Verdacht" fortführen. "Was ist von L-Theanin/Ashwagandha/'Nootropika' zu halten?" → Keine belastbare ADHS-spezifische Evidenz, keine Leitlinienempfehlung, Werbeversprechen sind kein Wirksamkeitsnachweis — Wechselwirkungen mit Medikation vorher mit Arzt/Apotheker klären.$$),

('medikamente', 'Medikamente-Modul: Vertiefung & Klienten-FAQ', $$Vertiefung: Methylphenidat blockiert überwiegend den Dopamin-/Noradrenalin-Transporter (Wiederaufnahme-Hemmung), Amphetamin-Derivate erhöhen zusätzlich die Freisetzung aus präsynaptischen Vesikeln — beide führen im präfrontalen Kortex zu besserer Signal-Rausch-Differenzierung (relevante Reize werden leichter von irrelevanten unterschieden). Atomoxetin baut seine Wirkung über mehrere Wochen auf — wichtig für Klient:innen, die nach wenigen Tagen enttäuscht sind. Beim Nachlassen der Wirkstoffkonzentration (oft später Nachmittag/Abend) kann es zu überschießendem Rückgang der Regulation kommen (Rebound: Reizbarkeit, Stimmungseinbruch) — für dich reines Beobachtungs-/Dokumentationsthema für die ärztliche Feinjustierung, niemals Anlass für eine eigene Anpassungsempfehlung.

Häufige Zusatzfragen: "Warum wirkt mein Medikament manche Tage stärker als andere?" → Mögliche Faktoren: Nahrungsaufnahme (manche Präparate werden je nach Magenfüllung unterschiedlich aufgenommen), Schlafqualität der Vornacht, Stresslevel, bei Frauen auch Zyklusphase — das darfst du dokumentieren helfen, die Einordnung bleibt ärztlich. "Habe ich Angst vor Abhängigkeit, ist das berechtigt?" → Bei leitliniengerechter, ärztlich begleiteter Einnahme ist das Risiko gering — ein häufiges, ernst zu nehmendes Sorgen-Thema, das fachlich beim Arzt geklärt werden sollte. "Darf ich mein Medikament am Wochenende weglassen (Drug Holiday)?" → Ausschließlich ärztlich zu entscheiden — du dokumentierst, wie sich Auslassen anfühlt/auswirkt, rätst nie dazu oder davon ab.$$),

-- Bereichsübergreifende Sonderthemen (Teil 4 des Handbuchs) — bewusst zu
-- zwei kompakten Einträgen zusammengefasst statt neun Einzelthemen.
(null, 'Sonderthemen: Frauen/Zyklus, Substanzen, Schichtarbeit/Jetlag', $$ADHS bei Frauen wird historisch häufiger übersehen/spät diagnostiziert, weil das klassische diagnostische Bild stark an äußerer Hyperaktivität (eher bei Jungen beobachtet) orientiert war — bei Frauen zeigt sich ADHS häufiger als innere Unruhe, Unaufmerksamkeit, Überforderung im Alltagsmanagement, emotionale Reizbarkeit, oft als "Stress" oder "Charakterzug" fehlgedeutet. Es gibt wachsende klinische Beobachtungen, dass der Östrogenspiegel die dopaminerge Funktion moduliert — viele Frauen berichten von Symptomverschlechterung in der zweiten Zyklushälfte (nach dem Eisprung, besonders kurz vor der Menstruation). Du darfst diesen Zusammenhang erklären und zu Tracking (Symptom-Tagebuch parallel zum Zyklus) ermutigen, aber keine hormonelle/medikamentöse Empfehlung geben. Perimenopause/Wechseljahre wird zunehmend als Phase beschrieben, in der sich ADHS-Symptome bei vielen Frauen deutlich verstärken — ernst nehmen, dokumentieren helfen, zur Ansprache bei Gynäkologie/Psychiatrie ermutigen. Schwangerschaft/Stillzeit: medikamentöse Behandlung ist ein hochsensibles, rein ärztliches Abwägungsthema, keine Beratungsrolle für dich außer emotionaler Begleitung.

Alkohol wird von vielen unbehandelten/unzureichend behandelten Erwachsenen unbewusst als "Runterkommen"-Strategie genutzt, stört aber die Schlafarchitektur (v.a. REM in der zweiten Nachthälfte) erheblich — der subjektive "schläft besser ein"-Effekt täuscht über schlechtere Schlafqualität hinweg; Konsummuster-Bewertung ist ärztlich/suchtmedizinisch. Nikotin wirkt dopaminerg/stimulierend (Selbstmedikations-Hypothese, erklärt überdurchschnittliche Raucherquoten bei ADHS) — Rauchentwöhnung ist kein Coaching-Thema, bei Interesse an spezialisierte Angebote verweisen. Bei jedem Hinweis auf problematischen Substanzkonsum generell: sachlich, nicht wertend registrieren, konsequent an Arzt/Suchtberatung verweisen, kein eigenes Coaching zur Konsumreduktion.

Bei Schichtarbeit gehen die üblichen Schlaf-/Licht-Empfehlungen implizit von Tagschicht aus — bei Wechsel-/Nachtschicht ist der Versuch, die innere Uhr überhaupt zu synchronisieren, oft wenig sinnvoll; professionelle Beratung zielt eher auf Schlafhygiene INNERHALB des jeweiligen Rhythmus (Verdunkelung tagsüber, feste Schlaf-Anker-Zeiten) — du darfst die allgemeinen Prinzipien (Externalisierung, feste Ketten, Lichtsteuerung) anwenden, solltest aber offen sagen, dass es dafür eigene arbeitsmedizinische Beratung gibt. Bei Jetlag/Reisen gelten dieselben Licht-Prinzipien wie bei Tageslicht — Faustregel: Richtung Osten reisen (Phasenvorverlagerung) ist meist schwerer zu bewältigen als Richtung Westen, ein reines Alltagswissens-Thema ohne medizinisches Risiko.$$),

(null, 'Sonderthemen: AuDHS, Komorbiditäten, Diagnostik, Genetik, Erwachsenen-ADHS, Beziehung', $$AuDHS (ADHS + autistische Züge/Diagnose gemeinsam) kann zu scheinbar widersprüchlichen Bedürfnissen führen: ADHS-Anteile profitieren oft von Neuheit/Abwechslung, autistische Anteile oft von maximaler Vorhersehbarkeit und Routine-Stabilität. Wenn Standard-"mehr Abwechslung einbauen"-Vorschläge auf Ablehnung stoßen, kann das ein Hinweis auf diese Gegenläufigkeit sein — dann mehr Vorsicht bei Veränderungsvorschlägen, mehr Betonung auf stabile Strukturen statt Neuheit.

Komorbiditäten, worauf achten (ohne zu diagnostizieren): Angststörungen sehr häufig komorbid — wiederholte, das Coaching-Thema übersteigende Angst (z.B. Panik vor Alltagssituationen) ist Überweisungsgrund. Depressive Symptomatik ist von der bei ADHS häufigen kurzen "emotionalen Dysregulation" abzugrenzen durch: anhaltend (über Wochen), gedrückte Stimmung mit Interessenverlust, Antriebslosigkeit — klassisches Überweisungssignal unabhängig davon, wie "gut begründbar" die Stimmung durch Alltagsstress erscheint. Burnout vs. ADHS-Erschöpfung: Burnout entsteht typischerweise als Reaktion auf anhaltende Überlastung in einem bestimmten Lebensbereich und bessert sich mit Entlastung; ADHS-typische Schwierigkeiten bestehen meist schon deutlich länger, kontextübergreifend, auch in entlasteten Phasen — bei Unsicherheit ist das ein diagnostisches Thema, du darfst den Unterschied erklären, aber keine Einschätzung abgeben, welches vorliegt.

Diagnostikprozess (rein informativ beschreibbar, keine Diagnosestellung): eine seriöse Erwachsenendiagnostik umfasst ein ausführliches klinisches Gespräch, strukturierte Fragebögen/Skalen, wenn möglich Fremdanamnese (z.B. Schulzeugnisse), Ausschluss anderer Erklärungen — durchgeführt von Fachärzt:innen oder spezialisierten Psychotherapeut:innen, nie vom Coach. Wartezeiten sind in Deutschland oft lang, die Zeit bis zur Diagnose kann bereits sinnvoll für Psychoedukation und erste Routinenarbeit genutzt werden — genau die Funktion dieses Programms für die Zielgruppe "Verdacht".

Genetik: ADHS gilt mit geschätzter Erblichkeit von grob 70-80% (Zwillingsstudien) als eine der am stärksten genetisch bedingten psychischen Störungen, daneben spielen Umweltfaktoren eine Rolle — für Klient:innen oft entlastend ("liegt nicht an schlechter Erziehung"), aber keine individuelle Ursachenzuschreibung vornehmen.

Erwachsenen-ADHS zeigt sich anders als im Kindesalter: seltener äußere Hyperaktivität, häufiger innere Unruhe, chronische Prokrastination, Zeitmanagement-Schwierigkeiten, emotionale Reizbarkeit, Gefühl "unter dem eigenen Potenzial zu bleiben" — viele Diagnosen erst im Erwachsenenalter, wenn frühere Kompensationsstrategien (Intelligenz, externe Struktur durch Schule) bei zunehmender Eigenverantwortung nicht mehr ausreichen.

Beziehung/Familie/Arbeit: häufige Themen sind die "wie ein zusätzliches Elternteil"-Dynamik durch ungleiche Erinnerungs-/Organisationslast, Elternschaft mit ADHS (eigene Strukturschwierigkeiten treffen auf nicht verschiebbare Kinderbedürfnisse, hoher Leidensdruck/Schuldgefühle), sowie Arbeitsplatzthemen (Deadlines, Reizüberflutung im Großraumbüro). Du darfst Alltagsstruktur-Lösungen anbieten (gemeinsame externe Systeme), aber Paar-/Beziehungsdynamiken sind Paartherapie-Terrain, Erziehungsberatung nicht dein Mandat, Rechtsfragen zu Nachteilsausgleichen gehören an Integrationsamt/Fachanwalt/ADHS Deutschland e.V.$$),

-- Ergänzung zur bestehenden "Rolle & Grenzen"-Wissensbasis (0047) um
-- konkrete neue Gesprächsmomente aus Teil 5 des Handbuchs.
(null, 'Rolle & Grenzen: weitere schwierige Gesprächsmomente', $$"Kannst du mir sagen, ob ich ADHS habe?" → "Das kann und darf ich nicht beurteilen — das ist fachärztliche/psychotherapeutische Diagnostik. Was ich anbieten kann: wir arbeiten an den Themen, die dich beschäftigen, unabhängig vom offiziellen Befund." Diese Trennung ist zentral für die Zielgruppe "Verdacht ohne Diagnose".

"Sag mir einfach, was ich tun soll." → Verständlicher Wunsch nach Entlastung, aber eine Falle: direkte Lebensentscheidungen vorzugeben verlässt die Coaching-Rolle. Besser: "Ich gebe dir gerne Optionen und meine fachliche Einschätzung zu Mechanismen — die Entscheidung, was für dich passt, triffst du. Lass uns zwei, drei Möglichkeiten durchgehen."

"Hast du wirklich Ahnung/welche Qualifikation hast du?" → Ehrlich und selbstbewusst beantworten: transparent machen, dass Coaching (kein Arzt/Therapeut) auf welcher Wissensbasis arbeitet (Leitlinien, Fachliteratur, dieses Programm), und dass bestimmte Fragen bewusst an Fachpersonen weitergegeben werden. Selbstbewusstsein bezieht sich auf Coaching-Kompetenz, nie auf vorgetäuschte medizinische Expertise.

Bitte um eine Bescheinigung/ein Attest/eine fachliche Einschätzung für Dritte (Arbeitgeber, Behörde) → klare Absage: liegt außerhalb der Coach-Befugnis und wäre potenziell rechtlich problematisch (Ausübung der Heilkunde ohne Erlaubnis, Heilpraktikergesetz §1) — Verweis an die behandelnde Fachperson, die eine solche Bescheinigung ausstellen darf.

Person stellt sich als minderjährig heraus (oder Zweifel am Alter entstehen) → das Programm ist ausdrücklich nur für Erwachsene: sofort ansprechen, Coaching für diese Person beenden, an altersgerechte Angebote verweisen (Kinder-/Jugendpsychiatrie, Familienberatung) — keine Fortführung "nur diesmal" oder "nur informell".

"Ich glaube, das Coaching bringt mir nichts / du verstehst mich nicht." → Nicht defensiv werden, konkret nachfragen: "Was genau fehlt dir — mehr Struktur, mehr Verständnis für deine Situation, andere Themen?" Feedback ernst nehmen; wenn sich zeigt, dass grundsätzlich ein anderes Format (Therapie statt Coaching) gebraucht wird, das offen ansprechen statt am Format festzuhalten.$$),

-- Kuratierte Auswahl aus dem 110-Begriffe-Lexikon: nur Begriffe, die
-- nirgendwo sonst in coach_wissen vorkommen UND für ein laufendes Gespräch
-- (nicht nur zum Nachschlagen für die Nutzerin selbst) relevant sind.
(null, 'Lexikon-Auszug: ADHS-Begriffe, die im Gespräch auftauchen können', $$Zeitblindheit (Time Blindness): Schwierigkeit, verstrichene Zeit oder die Dauer bis zu einem Ereignis intuitiv richtig einzuschätzen ("ich dachte, es waren 20 Min., es waren zwei Stunden") — externe, sichtbare Zeitanker (Timer, Uhren, akustische Signale) sind wirksamer als das eigene Zeitgefühl.

Rejection Sensitive Dysphoria (RSD): in der ADHS-Community verbreiteter, klinisch nicht offiziell anerkannter Begriff für eine ausgeprägte, oft überwältigende emotionale Reaktion auf tatsächliche oder wahrgenommene Zurückweisung/Kritik. Als bekanntes, nachvollziehbares Muster einordnen, nicht als offizielle Diagnose verwenden — bei starkem Leidensdruck an Psychotherapie verweisen.

Masking/Camouflaging: bewusstes oder unbewusstes Verbergen/Kompensieren von ADHS-Symptomen in sozialen/beruflichen Situationen (z.B. übermäßige Vorbereitung, Bewegungsdrang unterdrücken) — kostet erhebliche Energie, gilt als möglicher Grund, warum ADHS bei manchen (u.a. häufig bei Frauen) lange unerkannt bleibt. Relevant bei Berichten über chronische Erschöpfung durch "ständiges Funktionieren-Müssen".

Delay Aversion: Modell, das ADHS teilweise als ausgeprägte Abneigung gegen Warten/Belohnungsaufschub beschreibt — sofortige kleine Belohnungen werden gegenüber späteren größeren überproportional bevorzugt, erklärt u.a. Prokrastination und impulsive Entscheidungen.

Default Mode Network (DMN): Hirnnetzwerk, aktiv wenn keine gerichtete Aufgabe bearbeitet wird (Tagträumen). Bei ADHS wird eine gestörte Wechselregulation diskutiert — vereinfacht schaltet sich das "Ruhe-Netzwerk" schwerer ab, wenn Fokus gebraucht wird, was Ablenkbarkeit mit erklären kann.

Doom-Scrolling: anhaltendes, oft belastendes Scrollen durch negative Inhalte ohne bewusste Absicht aufzuhören — bei ADHS begünstigt durch Hyperfokus-Anfälligkeit und den neuheitsgetriebenen Belohnungsmechanismus, besonders relevant für die Abendroutine.

Objektpermanenz-Problem ("aus den Augen, aus dem Sinn"): umgangssprachlicher Begriff für die häufige Beobachtung, dass nicht sichtbare Aufgaben/Termine aus dem aktiven Bewusstsein "verschwinden" — zentrale Begründung für die Coaching-Strategie der Sichtbarkeit (Gegenstände offen platzieren, visuelle Trigger).

Eisenhower-Matrix (und warum sie bei ADHS oft nicht reicht): klassisches Priorisierungswerkzeug nach Dringlichkeit/Wichtigkeit — setzt voraus, dass "Wichtigkeit" allein motivierend wirkt. Bei ADHS, wo Motivation stärker über Interesse/Neuheit/Dringlichkeit läuft, reicht reine Kategorisierung oft nicht, um tatsächlich zu starten — als ergänzendes Denkwerkzeug, nicht als alleinige Lösung für Priorisierungsprobleme anbieten.

Pomodoro-Technik: feste Arbeitsintervalle (klassisch 25 Min.) mit kurzen Pausen — kann helfen, weil sie eine Aufgabe künstlich verkleinert und künstliche Dringlichkeit schafft. Kein Standardrezept: manche empfinden das Timer-Klingeln als störende Unterbrechung mitten im Hyperfokus, individuelles Ausprobieren wichtiger als die Technik selbst.

Motivational Interviewing (MI): Gesprächsansatz aus Suchtberatung/Psychotherapie, der Ambivalenz gegenüber Veränderung offen anspricht statt Ratschläge zu erteilen. Einzelne Grundhaltungen (offene Fragen, reflektierendes Zuhören, Autonomie respektieren) sind mit dem GROW-Modell kompatibel und nützlich, MI als vollständige Methode ist aber primär Therapie-/Beratungsformat.

Screening-Fragebögen (ASRS, Conners-Skalen, DIVA, WURS): standardisierte Selbstbeurteilungs-/Diagnostik-Fragebögen, die in einer ärztlichen/psychotherapeutischen ADHS-Diagnostik zum Einsatz kommen können. Du darfst sagen, dass solche Fragebögen existieren und beim Arzt/Psychotherapeuten als erster Schritt dienen können — kein Diagnoseinstrument im Coaching selbst, keine eigene Anwendung/Auswertung.

Selbstwirksamkeit (Bandura): das Vertrauen einer Person in die eigene Fähigkeit, eine Handlung erfolgreich auszuführen. Kleine, sicher erreichbare Erfolge (die "Tiny"-Experimente in jedem Modul) bauen Selbstwirksamkeit systematisch auf — ein Grund, warum konsequent mit kleinen statt großen ersten Schritten gearbeitet wird.

Neurodiversität: Perspektive, die neurologische Unterschiede (u.a. ADHS, Autismus) als natürliche Variation menschlicher Gehirnfunktion beschreibt statt ausschließlich als "Defizit". Als respektvoller Haltungsrahmen nützlich, ersetzt aber nicht die klinische Einordnung von Leidensdruck und Behandlungsbedarf.$$)

;
