-- Dritte Befüllungsrunde der Wissens-Basis (coach_wissen, 0046) — Quelle:
-- die von der Nutzerin bereitgestellte "AKA Content & Knowledge Library"
-- (122 nummerierte Wissens-Dossiers, aufgeteilt auf mehrere PDFs). Dieser
-- Teil deckt Dossiers 01-40 ab (Block A "ADHS-Alltag & Systemdesign" +
-- Block B "Biologie/Medikation/Selbststeuerung" + Anfang Block C
-- "Nährstoffe/Supplemente"). Dossiers 41-122 kommen in einer separaten
-- Migration (0053), da die Quelle auf drei PDFs verteilt war.
--
-- Kuratierungslogik (Nutzerin-Vorgabe: "ergänze gerne alles, was die
-- Supplemente angeht" + "insofern nötig und noch nicht vorhanden"):
-- Jedes Dossier folgt im Original dem Schema Wissensbaustein →
-- Mechanismus → Evidenz/Pro-Contra → Vortragsentwurf → Experiment →
-- Coaching-Lernfunktion → Content-Engine → Querverbindungen. Übernommen
-- wurde nur der faktische Kern (Wissensbaustein + Mechanismus +
-- Evidenzlage + Sicherheitshinweis + eine praktische Coaching-
-- Schlussfolgerung), umformuliert in Fließtext statt Dossier-
-- Kopfzeilen. NICHT übernommen: Vortragsentwurf (ihr persönliches
-- Redemanuskript für Content), Experiment/Beobachtungsprotokoll
-- (Recherche-/Filmprotokoll für ihre eigene Content-Produktion),
-- Content-Engine/Querverbindungen (Content-Marketing-Ideen) — das ist
-- Material für ihr eigenes Coaching-/Content-Geschäft, keine
-- Gesprächsgrundlage für Aka im Chat mit ihr selbst.
--
-- Vor dem Schreiben per grep geprüft: KEINE der acht Nährstoff-Dossiers
-- (Magnesium/Zink/Eisen/Vitamin D/Omega-3/B12/Folat/B6) war bisher als
-- eigener Eintrag vorhanden — echte Lücke, jetzt geschlossen. Die 20
-- Alltags-/Systemdesign-Dossiers aus Block A wurden zu drei
-- zusammengefassten Einträgen gebündelt statt 20 Einzelzeilen (sonst zu
-- viel Volumen für eine Tabelle, die komplett in jede Chat-Anfrage
-- eingebettet wird). Die meisten Block-B-Dossiers (Differenzialdiagnostik,
-- ADHS+Depression/Angst/Trauma) wurden bewusst NICHT übernommen — die
-- Coach-Grenzen/Weiterverweisungs-Logik ist über die bestehenden
-- "Rolle & Grenzen"-Einträge (0047) schon abgedeckt, eine Wiederholung in
-- neuen Worten bringt keinen Gesprächsmehrwert. Zwei Ausnahmen mit echtem
-- neuem Coaching-Frame wurden übernommen (Dossier 21/27/28 gebündelt).
insert into public.coach_wissen (bereich, titel, text) values

(null, 'ADHS-Alltagssysteme: Externalisieren statt merken', $$Grundprinzip: Wiederkehrende Entscheidungen und das Gedächtnis für Gegenstände/Aufgaben lassen sich nicht durch mehr Willenskraft verbessern, sondern durch externe Systeme, die die Erinnerungs- und Sucharbeit übernehmen. Konkrete Bausteine: feste "Landing Spots" für Schlüssel/Tasche/Ladegerät zu Hause (Cue statt Suchen), eine minimal bestückte Tasche mit festem Essential-Set + 30-Sekunden-Exit-Check, ein externes Notizsystem statt "im Kopf behalten" (Kalender, Checklisten, sichtbare Hinweise), sowie eine klare Trennung von Aufgabenlisten: Sammlung (alles) ≠ Heute (max. 3 Aufgaben) ≠ Nächster Schritt ≠ Später. Bei Kleidung/Morgen: eine kleine Zahl vorbereiteter Kombinationen ("Uniformprinzip") reduziert die morgendliche Entscheidungslast, ohne dass es um Stilverzicht geht — Fokusmodus und Stilmodus können koexistieren. Wichtig für Gespräche: Das ist alles Verhaltens-/Umweltdesign, keine ADHS-spezifisch belegte Therapie — die Wirkung wird über ein kleines persönliches Experiment (z. B. 7 Tage, eine Variable, Suchzeiten/vergessene Aufgaben zählen) geprüft, nicht behauptet. Coaching-Kernfrage: "Was suchst oder vergisst du wiederholt — und wo müsste es stattdessen automatisch auftauchen?"$$),

(null, 'ADHS-Alltagssysteme: Start, Übergänge, Rückkehr nach Ausfall', $$Viele ADHS-Alltagsprobleme sitzen nicht in der Aufgabe selbst, sondern an den Rändern: Start, Übergang, Wiedereinstieg. Startreibung: ein aufgeräumter, auf eine Aufgabe reduzierter Arbeitsplatz ("One-Task-Fläche") reduziert konkurrierende Reize; Timeboxing (z. B. 45-Minuten-Einheiten mit Pause) macht diffuse Vorhaben handhabbar — Wirkung hängt weniger an der exakten Zeit als an klarer Aufgabengrenze, Startsignal und sichtbarem Fortschritt. Übergänge: Aufgabenwechsel kosten bei ADHS oft überproportional viel Zeit ("40 Minuten verloren nach 90 Minuten Arbeit") — ein fester 10-Sekunden-Abschlussritus ("Wo bin ich? Was ist der nächste Schritt?") plus ein Startcue für die nächste Aufgabe reduziert diese Reibung. Rückkehr nach einer Pause/einem Ausfall: das wichtigste Prinzip ist Restart statt Aufholen — nach mehreren schlechten Tagen ist die erste Aufgabe NICHT, das Verpasste nachzuholen (das vergrößert den Wiedereinstieg zusätzlich), sondern zum kleinsten nächsten Schritt zurückzukehren. Prokrastination ist dabei nicht immer Faulheit, sondern kann Startreibung, Unklarheit, zu große Aufgabe ODER emotionale Vermeidung (Scham, Angst) sein — je nachdem greift "Aufgabe kleiner machen" oder es braucht mehr. Hyperfokus ist eine Ressource UND ein Risiko (Essen/Schlaf/Termine können verdrängt werden) — Ziel ist ein Exit-System (vorab definierte Stop-Signale), nicht das Wegtrainieren. Digitale Reize (Benachrichtigungen) sind eine der größten vermeidbaren Unterbrechungsquellen — Prioritätskanäle statt Totalverbot. Grundhaltung bei einem schlechten Tag: zuerst Zustand prüfen (Schlaf, Hunger, Reizlast, Stress, Emotion) statt sich zu bewerten, dann Aufgabe verkleinern oder Umgebung ändern — bei anhaltenden schweren Symptomen an Fachpersonal weiterverweisen.$$),

(null, 'ADHS-Alltag: Schlaf, Ernährung, Wasser, Morgenroutine, Motivation', $$Schlaf: Bei Erwachsenen mit ADHS sind subjektive Schlafprobleme in Studien häufiger berichtet als bei Menschen ohne ADHS, objektive Messwerte sind aber weniger konsistent — die einfache Gleichung "ADHS = Schlafmangel" ist zu grob. Praktisch hilfreich: Schlaf als System aus Aufstehzeit, Schlafdruck, Licht, Koffeinfenster und Abendübergang begreifen statt als reine Disziplinfrage; bei anhaltenden/starken Beschwerden können Schlafapnoe, Restless Legs, Depression oder Medikamente mitspielen — das gehört fachlich abgeklärt. Ernährung: Leitlinien bewerten restriktive/eliminierende ADHS-Diäten deutlich vorsichtiger, als Social Media suggeriert; hilfreich ist stattdessen ein wartungsarmes System (3-5 Standardgerichte + 1-2 Notfallgerichte), das auch an schlechten Tagen funktioniert, statt Perfektion anzustreben. Wasser: primär ein Sichtbarkeits-/Trigger-Thema (Flasche am festen Ort, Trigger an Übergängen), keine ADHS-Ursachenfrage — Dehydration kann kognitive Funktionen beeinflussen, das begründet aber keine pauschale "X-Liter"-Empfehlung. Morgenroutine: eine minimale Startsequenz (aufstehen, Wasser, Körper, Kleidung, Arbeitsplatz) schützt vor Überforderung besser als 15 optimierte Gewohnheiten auf einmal — jede zusätzliche Entscheidung ist eine zusätzliche Stelle, an der die Routine abbrechen kann. Motivation: entsteht bei ADHS nicht aus einem einzelnen "Dopaminmangel", sondern aus dem Zusammenspiel von Interesse, Dringlichkeit, Neuigkeit, Belohnung und erwartetem Aufwand — coaching-praktisch hilft es, bei fehlendem intrinsischem Interesse gezielt EINEN Hebel zu verändern (kürzerer Block, sichtbarer Fortschritt, externe Deadline, unmittelbares Feedback), statt die Person zu mehr Motivation aufzufordern.$$),

(null, 'ADHS-Coaching-Grundhaltung: Medikation, Verantwortung, Drei-Ebenen-Modell', $$Medikamente und Selbstmanagement sind kein moralischer Gegensatz ("Pille vs. Disziplin") — sie wirken auf unterschiedlichen Ebenen (Symptomlast/Neurotransmission vs. Verhalten/Umwelt/Fähigkeiten) und können sich ergänzen. Hilfreiches Modell für Gespräche: drei Ebenen einer Schwierigkeit — (1) Symptommanagement (z. B. Medikation), (2) Fähigkeiten/Strategien (Skills, Routinen), (3) Umwelt (Anforderungen senken, Struktur schaffen). Eine Lösung scheitert oft, weil nur eine Ebene bearbeitet wird, obwohl die Hürde auf einer anderen sitzt — Coaching-Frage: "Auf welcher der drei Ebenen sitzt die aktuelle Hürde?" Ethischer Grundsatz: ADHS ist keine Entschuldigung, aber eine Erklärung — eine Erklärung verändert die Wahl der Intervention (konkrete Funktionshürde statt moralische Bewertung), befreit aber nicht von Verantwortung für Umgang, Kommunikation und Reparatur. Wichtig in Gesprächen: nie eine Medikationsentscheidung oder -änderung im Coaching treffen oder nahelegen — das bleibt ärztliche Aufgabe; Coaching kann höchstens helfen, Beobachtungen für das Arztgespräch zu strukturieren ("Was möchtest du deinem Arzt konkret berichten?").$$),

('supplemente', 'Magnesium: Evidenzlage und Einordnung', $$Magnesium ist an zahlreichen enzymatischen Prozessen, neuromuskulärer Funktion und Energiestoffwechsel beteiligt — bei ausreichender Versorgung bedeutet "mehr" aber nicht automatisch "mehr Nutzen". Verschiedene Magnesiumsalze (z. B. -citrat, -glycinat, -oxid) unterscheiden sich in Löslichkeit, Bioverfügbarkeit und Verträglichkeit (v. a. Durchfallrisiko bei schlecht resorbierbaren Formen in hoher Dosis). Für ADHS speziell ist die Evidenz dünn: Eine systematische Review fand nur sechs experimentelle Studien, keine davon eine gut kontrollierte randomisierte Doppelblindstudie — die Autoren sahen keine ausreichende Evidenz für eine ADHS-Behandlung. Für Schlaf ist die Studienlage etwas breiter, aber mit gemischten Ergebnissen zur objektiven Schlafdauer. Praktische Einordnung fürs Gespräch: "Magnesium ist wichtig" ist kein Beleg dafür, dass zusätzliches Magnesium bei einer bestimmten Person etwas bewirkt — die sinnvolle Frage ist eher, ob überhaupt ein Mangel/geringer Status vorliegt und was genau damit gelöst werden soll. Keine pauschale Dosierungsempfehlung; bei Nierenproblemen oder bestimmten Medikamenten (z. B. manche Antibiotika) sind Wechselwirkungen möglich — das gehört ärztlich abgeklärt, nicht ins Coaching.$$),

('supplemente', 'Zink: Status, ADHS-Forschung und Kupfer-Wechselwirkung', $$Zink ist essenziell für zahlreiche Enzyme, Protein-/DNA-Synthese und Immunfunktion. Wichtigste Sicherheitslektion: chronisch hohe Zinkzufuhr kann die Kupferversorgung beeinträchtigen (Zink-Kupfer-Antagonismus) — deshalb ist Dauereinnahme ohne Anlass nicht unbedenklich. Die ADHS-Supplementliteratur zu Zink ist kleiner und heterogener, als Social-Media-Claims suggerieren; ein möglicher Nutzen wurde vor allem in Populationen mit nachgewiesenem Mangel diskutiert, nicht als universelle Empfehlung. Praktische Einordnung: Die relevante Frage ist nicht "Ist Zink gut?" (ein essenzieller Nährstoff ist per Definition wichtig), sondern ob eine konkrete Person tatsächlich mehr braucht, als sie über die Ernährung bekommt, und ob daraus ein messbarer Effekt folgt — das ist der Unterschied zwischen Ernährungsphysiologie und Supplementmarketing. Coaching-Ansatzpunkt: Ernährung/Status zuerst betrachten (welche Zinkquellen werden schon gegessen?), keine langfristige Hochdosis-Einnahme ohne medizinische Begründung.$$),

('supplemente', 'Eisen/Ferritin: Zusammenhang mit ADHS und Vorsicht bei Supplementierung', $$Eisen ist zentral für Sauerstofftransport (Hämoglobin) und zahlreiche Enzyme; im Gehirn spielt es u. a. im Dopaminstoffwechsel eine Rolle. Assoziationen zwischen niedrigem Ferritin und ADHS-Symptomen sind beschrieben, aber Assoziation ist keine Kausalität, und ein statistischer Zusammenhang beweist keinen klinischen Nutzen einer Supplementierung. Wichtiger Sicherheitshinweis: Eisen ist kein "harmloses" Wellness-Supplement — unnötige Zufuhr bei nicht nachgewiesenem Mangel kann schaden (u. a. weil der Körper überschüssiges Eisen schlecht ausscheidet). Deshalb explizit: kein Eisen-Selbstexperiment ohne Laborwert. Coaching-Haltung: Bei Verdacht auf Mangel (z. B. Müdigkeit, Konzentrationsprobleme zusammen mit anderen Anzeichen) gehört das über einen Bluttest (Ferritin/Hämoglobin) ärztlich abgeklärt — "Mangel behandeln" und "ADHS behandeln" sind zwei unterschiedliche Aussagen, die nicht vermischt werden dürfen.$$),

('supplemente', 'Vitamin D: Status, ADHS-Forschung und Überversorgung', $$Vitamin D wirkt eher wie ein Hormon-System mit vielfältigen Funktionen als wie ein klassisches Vitamin. Ein niedriger gemessener Status kann mit verschiedenen gesundheitlichen Zuständen assoziiert sein — das beweist aber nicht, dass eine Supplementierung diesen Zustand behandelt. Es gibt RCTs und Meta-Analysen zu Vitamin D und ADHS, aber keine ausreichende Grundlage, um daraus eine universelle Empfehlung abzuleiten; am ehesten relevant erscheinen Subgruppen mit tatsächlich niedrigem Ausgangsstatus. Sicherheitsaspekt: Vitamin D ist fettlöslich und kann bei dauerhafter Überdosierung zu einer echten Überversorgung führen (u. a. Hyperkalzämie-Risiko) — "mehr hilft mehr" gilt hier ausdrücklich nicht. Praktisch sinnvoller Einstieg ist ein gemessener 25(OH)D-Blutwert statt einer pauschalen Hochdosis auf Verdacht. Coaching-Frage: "Ist das ein nachgewiesener Mangel — oder ein Internet-Claim?"$$),

('supplemente', 'Omega-3 (EPA/DHA): Evidenzlage bei ADHS', $$Omega-3-Fettsäuren (v. a. EPA/DHA) sind eines der bekanntesten ADHS-Supplementthemen — die Studienlage ist aber deutlich zurückhaltender, als der öffentliche Ruf vermuten lässt. Eine Review mit sieben randomisiert-kontrollierten Studien und rund 926 Kindern fand keinen statistisch signifikanten Vorteil auf einer gängigen ADHS-Symptom-Ratingskala (Conners). Die bisherige RCT-Literatur betrifft zudem überwiegend Kinder/Jugendliche, nicht Erwachsene. Wichtig für die Bewertung einzelner Studien: Population, genaue EPA/DHA-Zusammensetzung, Dosis, Studiendauer und gemessener Endpunkt entscheiden stark über die Aussagekraft — ein einzelner positiver Treffer ersetzt keine Gesamtevidenz. Praktisch unproblematisch und mit breiterer allgemeiner Evidenz unterlegt ist Omega-3 aus Ernährungssicht (fetter Fisch); als gezielte "ADHS-Therapie" ist die Erwartungshaltung dagegen zu dämpfen. Coaching-Formulierung: nicht "Omega-3 hilft bei ADHS", sondern "Omega-3 ist ernährungsphysiologisch sinnvoll, ein spezifischer ADHS-Effekt ist wissenschaftlich nicht gut abgesichert."$$),

('supplemente', 'Vitamin B12, Folat/5-MTHF und B6: Nervensystem, Mangel und Grenzen', $$Drei B-Vitamine, die in Supplement-Diskussionen oft vermischt werden, obwohl sie unterschiedlich zu bewerten sind. B12 ist für die Funktion des Nervensystems relevant; ein NACHGEWIESENER Mangel kann neurologisch/hämatologisch relevant sein und dessen Korrektur ist medizinisch sinnvoll — das ist aber eine andere Aussage als "B12 verbessert bei ausreichendem Status die Konzentration". Folat/Folsäure/5-MTHF sind chemisch NICHT identisch (unterschiedliche Aufnahme/Umwandlung) — Studienergebnisse zu einer Form lassen sich nicht automatisch auf eine andere übertragen; die stärkste Evidenz betrifft allgemeine Versorgung und bestimmte Lebensphasen (z. B. Schwangerschaft), nicht spezifisch ADHS. Vitamin B6 ist Coenzym u. a. der Neurotransmitter-Synthese — das klingt nach einem überzeugenden "Nootropikum"-Argument, ist aber genau deshalb mit Vorsicht zu behandeln: hohe bzw. chronische B6-Zufuhr wird mit peripherer Neuropathie in Verbindung gebracht, "wasserlöslich" bedeutet also NICHT automatisch risikofrei. Gemeinsame Coaching-Linie für alle drei: Mangeltherapie (bei nachgewiesenem Mangel) und allgemeine kognitive Optimierung sind zwei verschiedene Fragestellungen — bei neurologischen Symptomen oder hohen Dosen gehört das ärztlich abgeklärt, nicht gecoacht.$$);
