-- Vierte Ergänzungsrunde der Wissens-Basis (coach_wissen, 0046). Quelle:
-- "AKA Content & Knowledge Library — Researched Revision, Dossiers 81-100"
-- (PDF, Stand 14.08.2026), die die Nutzerin per ChatGPT hat überarbeiten
-- lassen, nachdem 0054 festgestellt hatte, dass die Dossiers 61-122 der
-- Vorgängerfassung reine Themen-Platzhalter ohne Inhalt waren.
--
-- BEFUND ZUR NEUEN QUELLE: Die Überarbeitung ist ein echter Fortschritt,
-- aber ungleichmäßig. Die Supplement-Dossiers 81-86 (Block D: NAC,
-- Acetyl-L-Carnitin, CoQ10, Urolithin A, Kreatin/Schlafentzug,
-- Supplement-Stacking) enthalten jetzt tatsächlich konkrete Fakten:
-- Studiendesign, Teilnehmerzahlen, Jahr, teils PMID. Das sind exakt die
-- Themen, die 0054 namentlich als "reine Platzhalter" aufgeführt hatte —
-- hier jetzt echte Lücken geschlossen. Die 13 Block-F-Dossiers 87-100
-- ("ADHS und Partnerschaft/Sexualität/Scheitern/Scham/Trauma/Depression/
-- Angst/Burnout/Schlafstörungen/Alkohol/Geld/Schulden/Karriere/Führung")
-- sind dagegen weiterhin größtenteils Gerüst: Die Abschnitte
-- Studientyp/Pro-Contra/Sicherheit/Coaching-Transfer/Vortragsregel sind
-- für alle 13 Themen WORTIDENTISCH (derselbe generische Textbaustein),
-- der Abschnitt "Was die Evidenz tatsächlich hergibt" ist bei den meisten
-- leer, und sogar der Quellenapparat (vier Referenzen) wird für alle 13
-- Themen identisch wiederverwendet statt pro Thema neu recherchiert zu
-- sein — die Quellen sind also nur locker an ihr jeweiliges Thema
-- gekoppelt. Extrahiert wurde ausschließlich das, was im Eröffnungssatz
-- jedes Dossiers tatsächlich als konkreter Fakt (Studienjahr, Odds
-- Ratio, Stichprobengröße, Definitionsabgrenzung) stand — nichts wurde
-- aus eigenem Wissen ergänzt oder aus dem generischen Rahmentext
-- "plausibilisiert".
--
-- BEWUSST AUSGESCHLOSSEN:
-- - Dossier 88 "ADHS und Sexualität/Intimität": im Eröffnungssatz und im
--   gesamten Dossier kein einziger extrahierbarer Fakt (nur "discuss
--   only within clear boundaries" als Warnhinweis) — nichts zum
--   Übernehmen vorhanden, und das Thema läge ohnehin außerhalb dessen,
--   was ohne echte Evidenzgrundlage in eine bei jeder Chat-Anfrage
--   mitgeschickte Wissensbasis gehört.
-- - Dossier 95 "ADHS und Schlafstörungen": der einzige konkrete Fakt
--   (subjektive Schlafprobleme häufiger berichtet als objektiv messbar)
--   steht wortgleich bereits in 0053 ("ADHS-Alltag: Schlaf, Ernährung,
--   Wasser, Morgenroutine, Motivation") — echtes Duplikat, nicht erneut
--   aufgenommen.
-- - KEIN Vortragsentwurf, keine Experiment-/Beobachtungsprotokoll-,
--   Coaching-Lernfunktions- oder Content-Engine-Abschnitte übernommen —
--   wie bei 0053/0054 ist das Material für das eigene Coaching-/
--   Content-Geschäft der Nutzerin, kein Gesprächswissen für Aka.
--
-- BESONDERE SORGFALT BEI BLOCK F (Coaching-vs.-Therapie-Grenze): Die
-- Dossiers 91-93/96 (Trauma/Depression/Angst/Sucht) und 89-90
-- (Scheitern/Scham/Stigma) liegen inhaltlich nah an klinischem Terrain.
-- Geprüft wurde in jedem Fall, ob der tatsächliche Dossier-Inhalt über
-- reine Epidemiologie (Prävalenz-/Odds-Ratio-Zahlen, Definitionsklärung)
-- hinausgeht und in Therapietechnik, Traumaverarbeitung oder
-- Krisenintervention kippt — das war bei KEINEM der Dossiers der Fall,
-- die tatsächlichen Inhalte sind ausschließlich Zahlen/Korrelationen
-- plus derselbe Grenz-Hinweis, der ohnehin in jedem Block-F-Dossier
-- steht ("nicht diagnostizieren, an Fachperson verweisen"). Die neuen
-- Einträge liefern daher NUR den sachlichen Rahmen (wie häufig, welche
-- Unterscheidung), keine Gesprächstechnik zur Bearbeitung von Scham/
-- Trauma — die entsprechende Gesprächsführung bleibt bei den
-- bestehenden 0047-Einträgen ("Umgang mit Scham, Widerstand und
-- Rückschlägen", "Red-Flag-Protokoll"), auf die in den neuen Einträgen
-- ausdrücklich verwiesen statt sie zu wiederholen. Wäre bei einem
-- dieser Dossiers tatsächlich Therapietechnik oder Krisenintervention
-- als Inhalt vorgefunden worden, wäre das Dossier komplett
-- ausgeschlossen worden — kam hier nicht vor.
--
-- ZUSAMMENFASSUNG DER GRUPPIERUNG: 87 (Partnerschaft) + 99 (Karriere) +
-- 100 (Führung) zu einem Eintrag (gemeinsames methodisches Fazit:
-- heterogene, kontextabhängige Befundlage); 89 (Scheitern) + 90 (Scham/
-- Stigma) zu einem Eintrag; 91 (Trauma) + 92 (Depression) + 93 (Angst) +
-- 96 (Sucht) zu einem Komorbiditäts-Eintrag; 94 (Burnout), 97+98
-- (Geld/Schulden) sowie die sechs Supplement-Dossiers 81-86 jeweils
-- eigenständig bzw. paarweise. bereich = 'supplemente' für die
-- Supplement-Einträge (bestehender Wert), bereich = null für die
-- Block-F-Einträge (bestehender Wert für allgemeines ADHS-Wissen ohne
-- eigenes Modul) — kein neuer bereich-Wert eingeführt.

insert into public.coach_wissen (bereich, titel, text) values

('supplemente', 'NAC (N-Acetylcystein): Glutathion-Mechanismus vs. psychiatrische Evidenz', $$N-Acetylcystein (NAC) liefert Cystein als Baustein für die körpereigene Glutathion-Synthese — Glutathion ist eines der wichtigsten antioxidativen Systeme des Körpers. Dieser Mechanismus ist real und gut belegt, wird in Werbung aber oft unzulässig verkürzt zu "NAC entgiftet das Gehirn". NAC wurde in mehreren psychiatrischen Kontexten (u. a. Zwangsspektrum, Substanzgebrauch, affektive Störungen) klinisch untersucht — die Ergebnisse sind aber indikationsspezifisch und uneinheitlich: Ein Effekt bei einem psychiatrischen Störungsbild lässt sich nicht automatisch auf ein anderes übertragen, geschweige denn auf ADHS. Eine 2024 systematische Übersichtsarbeit zu Ernährungsinterventionen/Supplementen bei ADHS fand für NAC keine ausreichende ADHS-spezifische Evidenz. Für ein Gespräch bedeutet das: "Glutathion ist wichtig für den Körper" ist eine korrekte, aber für die Bewertung von NAC bei ADHS irrelevante Aussage — die relevante Frage ist, ob NAC in kontrollierten Studien bei genau diesem Störungsbild etwas bewirkt, nicht ob der zugrundeliegende Mechanismus plausibel klingt. Coaching-Takeaway: NAC sollte im Gespräch als "Wirkstoff mit pharmakologischer Forschungsgeschichte in bestimmten psychiatrischen Bereichen", nicht als generisches "Gehirn-Entgiftungs-Supplement" eingeordnet werden — bei Interesse eher fragen, welches konkrete Problem gelöst werden soll, als den Mechanismus als Wirkbeleg zu nehmen.$$),

('supplemente', 'Acetyl-L-Carnitin: Mitochondrien-Mechanismus ohne belegten ADHS-Nutzen', $$Carnitin (und seine Acetyl-Form) ist am Transport von Fettsäuren in die Mitochondrien beteiligt, wo sie zur Energiegewinnung verstoffwechselt werden — ein biochemisch gut beschriebener Mechanismus. Daraus wird im Supplement-Marketing gern die Behauptung "mehr Energie fürs Gehirn" abgeleitet. Für ADHS speziell zeigt sich aber ein klares Bild: Randomisierte, doppelblinde Studien zu L-Carnitin/Acetyl-L-Carnitin bei Kindern haben keinen belastbaren klinischen ADHS-Nutzen etabliert — die Ergebnisse waren negativ oder nicht schlüssig. Wichtig für die Einordnung ist die klare Trennung zwischen zwei unterschiedlichen Aussagen: "Carnitin ist an der mitochondrialen Energiegewinnung beteiligt" (Biochemie, unstrittig) und "Acetyl-L-Carnitin verbessert ADHS-Symptome" (klinische Wirksamkeitsbehauptung, durch die vorliegenden Studien nicht gestützt). Ein plausibler Mitochondrien-Mechanismus ist kein Ersatz für eine tatsächlich gemessene Symptomverbesserung. Coaching-Takeaway: Bei einem gehörten "Carnitin gibt mehr Energie fürs Gehirn"-Claim lohnt sich die Rückfrage, ob damit der Stoffwechselmechanismus oder eine tatsächlich gemessene ADHS-Symptomverbesserung gemeint ist — beides wird im Marketing gern vermischt, ist aber wissenschaftlich zweierlei.$$),

('supplemente', 'Coenzym Q10: Mitochondrien-Cofaktor, keine ADHS-Evidenz', $$Coenzym Q10 (CoQ10) ist ein zentraler Cofaktor der mitochondrialen Elektronentransportkette (Energiegewinnung) und wirkt zugleich antioxidativ. Eine 2025 Übersichtsarbeit zu acht klinischen Humanstudien fand gemischte Ergebnisse zu kognitiven Effekten — kein einheitliches Bild. Eine 2026 Metaanalyse von fünf randomisiert-kontrollierten Studien (insgesamt 474 Teilnehmende) fand eine moderate Verbesserung depressiver Symptome unter CoQ10, aber keinen signifikanten Effekt auf Müdigkeit/Fatigue — wichtig: Das sind Studien zu Depression und Fatigue, keine ADHS-Studien, und lassen sich nicht 1:1 übertragen. Für ADHS speziell bleibt die Evidenzlage abwesend bzw. unzureichend — es gibt schlicht keine belastbare CoQ10-Forschung zu ADHS-Symptomen. Das ist ein gutes Beispiel dafür, wie leicht "zeigt Wirkung bei X" (hier: depressive Symptome) im Gespräch fälschlich zu "zeigt Wirkung bei ADHS" verkürzt wird, obwohl beide Störungsbilder unterschiedliche Mechanismen und Studienlagen haben. Coaching-Takeaway: Bei CoQ10-bezogenen Aussagen genau nachfragen, für welches Störungsbild die zitierte Studie eigentlich lief — ein Depressions- oder Fatigue-Befund ist kein ADHS-Beleg, auch wenn beide Themen im Wellness-Kontext oft in einem Atemzug genannt werden.$$),

('supplemente', 'Urolithin A: Mitophagie-Forschung zu Muskeln, nicht zu ADHS/Kognition', $$Urolithin A ist ein aus dem Darmmikrobiom gebildeter Postbiotikum-Stoff, der als Aktivator der Mitophagie (zelluläres "Recycling"-System für beschädigte Mitochondrien) erforscht wird. Die vorhandene Humanforschung betrifft fast ausschließlich Muskel-bezogene Endpunkte, nicht ADHS oder Kognition: Eine 2022 randomisiert-placebokontrollierte Studie mit 66 Erwachsenen (65-90 Jahre), 1.000mg/Tag über vier Monate, zeigte eine verbesserte Muskelausdauer gegenüber Placebo. Eine weitere Studie an Erwachsenen mittleren Alters berichtete nach vier Monaten und zwei getesteten Dosen eine Muskelkraftsteigerung von rund 12%, wobei der primäre Endpunkt (Spitzenleistung) nicht signifikant war. Für eine ADHS- oder Kognitions-Indikation existiert keine etablierte Evidenzgrundlage — das ist bislang schlicht kein untersuchtes Anwendungsgebiet dieses Stoffs. Coaching-Takeaway: Urolithin A ist ein Beispiel für ein Supplement mit echter, aber eng umgrenzter Studienbasis (ältere/mittelalte Erwachsene, Muskelfunktion) — bei einem Wunsch nach "mehr Energie/Fokus" über Urolithin A ist wichtig zu klären, dass die vorliegende Forschung von einem ganz anderen Zielbereich (Muskeln, nicht Gehirn/ADHS) handelt.$$),

('supplemente', 'Kreatin bei akutem Schlafentzug: interessantes Studiendesign, keine Schlafmangel-Lösung', $$Akuter Schlafentzug wird in der Forschung gern als "Stresstest" genutzt, um Hypothesen zum Gehirn-Energiestoffwechsel zu prüfen — das ist ein Forschungsdesign, keine Behandlungsempfehlung. Eine 2024 kontrollierte Humanstudie gab Teilnehmenden während rund 21 Stunden Schlafentzug eine einmalige Kreatin-Dosis (0,35g/kg) und beobachtete Verbesserungen bei Verarbeitungsgeschwindigkeit/kognitiver Leistung sowie Veränderungen energiereicher Phosphat-Metaboliten im Gehirn (per Bildgebung gemessen). Eine 2026 systematische Übersichtsarbeit fand insgesamt nur fünf geeignete Studien zu diesem Thema und beschreibt die Gesamtevidenz als "frühen positiven Trend bei erheblicher Unsicherheit" — explizit keine gesicherte Wirksamkeit. Wichtig für die Einordnung: Das Studiendesign testet eine akute Extremsituation (fast ein Tag ohne Schlaf) mit einer einmaligen Dosis unter Laborbedingungen — daraus folgt keine Rechtfertigung, gewöhnliche Müdigkeit oder chronischen, alltäglichen Schlafmangel mit Kreatin statt mit tatsächlichem Schlaf zu behandeln. Coaching-Takeaway: Kreatin bei Schlafentzug ist ein spannendes Grundlagenforschungsthema, aber kein Ersatz-Werkzeug für zu wenig Schlaf — bei chronischer Müdigkeit bleibt die Frage nach der eigentlichen Schlafmenge/-qualität der richtige erste Ansatzpunkt, nicht ein Supplement.$$),

('supplemente', 'Supplement-Stacking: Interaktionen, Redundanzen und Entscheidungslogik', $$Je mehr Präparate gleichzeitig eingenommen werden ("Stacking"), desto schwerer wird es, Wirkung UND Sicherheit einem einzelnen Bestandteil zuzuordnen. Ein persönlicher Supplement-Stack kann unbemerkt doppelte Nährstoffquellen enthalten (z. B. dasselbe Mineral in Multivitamin plus Einzelpräparat), sich überschneidende pharmakologische Wirkmechanismen, Wechselwirkungen mit Medikamenten, und am Ende ein Ergebnis, das sich keinem einzelnen Bestandteil mehr zuordnen lässt (konfundierte Outcomes). Keine einzelne Studie validiert einen komplexen, individuell zusammengestellten Stack — wer fünf Präparate gleichzeitig nimmt und eine Wirkung bemerkt, hat de facto ein unkontrolliertes Selbstexperiment mit mehreren gleichzeitigen Variablen durchgeführt, nicht einen belegten Effekt nachgewiesen. Die methodisch korrekte Herangehensweise: Zuerst die gesamte tägliche Zufuhr jedes Inhaltsstoffs über alle Produkte hinweg zusammenrechnen (nicht Produkt für Produkt isoliert betrachten), dann jeweils nur eine Variable nach der anderen ändern und beobachten. Das verbessert die Zuordnung von Wirkung/Nebenwirkung, ersetzt aber keine ärztliche Begleitung, sobald ein Risiko (Wechselwirkungen, bestehende Medikation, Vorerkrankungen) im Raum steht. Coaching-Takeaway: Bei jemandem mit mehreren gleichzeitig eingenommenen Präparaten zuerst eine vollständige Liste erstellen (was, wie viel, seit wann) — das allein deckt oft schon Redundanzen auf, bevor überhaupt über Wirkung diskutiert wird.$$),

(null, 'ADHS und Burnout: zwei unterschiedliche Konzepte', $$Burnout ist nach ICD-11 als "occupational phenomenon" definiert — ein Ergebnis von chronischem, nicht erfolgreich bewältigtem Arbeitsstress — mit drei Kernmerkmalen: Erschöpfung, zunehmende mentale Distanz bzw. Zynismus gegenüber der eigenen Arbeit, und ein Gefühl reduzierter Leistungsfähigkeit. Burnout ist explizit KEIN Synonym für ADHS und keine eigenständige medizinische Diagnose. Als Hypothese (nicht als belegte Kausalität) wird diskutiert, dass ADHS die Anfälligkeit für Burnout erhöhen kann — u. a. durch den chronischen Mehraufwand, den das Kompensieren exekutiver Funktionsschwierigkeiten kostet, einen ungünstigen Fit zwischen Anforderungen und individuellen Fähigkeiten ("Mismatch"), sowie zusätzliche organisatorische Belastung. Das ist eine plausible Erklärung, kein bewiesener Wirkmechanismus. Für die Einschätzung im Gespräch ist es hilfreicher, auf die drei definierenden Burnout-Kriterien selbst zu schauen (Erschöpfung / Zynismus-Rückzug / wahrgenommene Wirksamkeit) statt auf einen diffusen Gesamteindruck von "Ich bin fertig". Coaching-Takeaway: Bei Verdacht auf Burnout nicht vorschnell "das ist eben ADHS" sagen — stattdessen die drei Kernmerkmale und den Arbeitskontext getrennt ansehen; bei tatsächlichem Burnout-Verdacht gilt wie bei anderen klinisch relevanten Zuständen: an eine Fachperson verweisen, nicht im Coaching eigenständig "bearbeiten".$$),

(null, 'ADHS, Geld und Schulden: Befundlage und Coaching-Ansatz', $$Eine 2019 Studie verglich 45 Erwachsene mit ADHS mit 51 Kontrollpersonen ohne ADHS: Die ADHS-Gruppe berichtete häufiger von einer schlechteren finanziellen Situation, mehr Schulden und mehr impulsiven Käufen, und schnitt in standardisierten Tests zu finanzieller Kompetenz und zukunftsbezogener Entscheidungsfindung schlechter ab — eine einzelne, kleine Studie, kein Beweis für ein universelles Muster bei jeder Person mit ADHS. Wichtig für Gespräche: Schulden sind kein diagnostisches Kriterium für ADHS und keine automatische Folge — aber finanzielle Entscheidungsschwierigkeiten können, wo vorhanden, coaching-relevant sein. Der sinnvolle Ansatz folgt denselben Prinzipien wie andere ADHS-Alltagsthemen: Sichtbarkeit statt Vermeidung (Kontostand/Rechnungen aktiv anschauen statt wegzuschieben), Reibungsreduktion durch Automatisierung (Daueraufträge/automatisiertes Sparen, damit die Entscheidung einmal statt wiederholt getroffen wird), und bei Beträgen oder Komplexität, die über coaching-taugliche Selbsthilfe hinausgehen, eine Weiterverweisung an Schuldner-/Finanzberatung. Coaching-Takeaway: Bei Geld-/Schuldenthemen nicht moralisieren ("warum kannst du nicht einfach sparen") — sondern wie bei anderen Alltagssystemen nach Sichtbarkeit und Automatisierung fragen, und bei tatsächlicher Überschuldung konsequent an eine Schuldnerberatung verweisen statt es im Coaching lösen zu wollen.$$),

(null, 'ADHS: wiederholtes Scheitern, Scham und Stigma-Forschung', $$Eine 2026 systematische Übersichtsarbeit dokumentierte bei Erwachsenen mit ADHS mehrere Stigma-Formen (selbst wahrgenommenes, öffentliches und strukturelles Stigma) — internalisiertes (Selbst-)Stigma war dabei mit schlechterem Selbstwertgefühl assoziiert. Passend dazu unterstützt eine ältere (2014) systematische Übersichtsarbeit zum Selbstwertgefühl bei Erwachsenen mit ADHS ein nachvollziehbares Muster: Wiederholte funktionale Ausfälle (verpasste Fristen, vergessene Zusagen und Ähnliches), die sich über die Zeit ansammeln, hängen mit geringerem Selbstwertgefühl bzw. Selbstbewertungsproblemen zusammen. Wichtig für die Einordnung: Das ist eine Korrelation zwischen angesammelten Scheitererfahrungen und Selbstwert — kein Beleg dafür, dass "ADHS automatisch zu Scheitern führt"; diese verkürzte Kausalaussage geht über die Studienlage hinaus. Für ein Gespräch bedeutet das: Scham-Muster bei ADHS haben oft eine nachvollziehbare Entstehungsgeschichte (wiederholte erlebte Funktionsausfälle plus gesellschaftliches Stigma) und sind damit eine verständliche, keine "übertriebene" Reaktion. Coaching-Takeaway: Diese Forschung liefert die sachliche Begründung dafür, Scham ernst zu nehmen statt zu relativieren — die eigentliche Gesprächsführung dabei (Validieren, zur Handlung zurückführen) ist bereits in den bestehenden Scham-/Rückschlag-Leitlinien beschrieben und wird hier nicht wiederholt.$$),

(null, 'ADHS-Komorbiditäten: Zahlen zu Angst, Depression, Sucht und PTBS', $$Eine große 2023 Übersichtsarbeit/Metaanalyse zu Komorbiditäten bei erwachsenen ADHS-Betroffenen fand gegenüber Menschen ohne ADHS deutlich erhöhte gepoolte Odds Ratios: rund 5,0 für Angststörungen, rund 4,5 für die Major Depression, rund 4,6 für Substanzgebrauchsstörungen. Separat fand eine 2025 systematische Übersichtsarbeit zur Komorbidität von ADHS und PTBS bei Erwachsenen (21 eingeschlossene Studien) eine berichtete Prävalenzspanne von 28-36% — die Studien waren aber zu heterogen für eine gepoolte Gesamtzahl. Entscheidend für die Einordnung: Assoziation ist keine Kausalität — diese Zahlen zeigen nicht, dass ADHS Angst/Depression/Sucht/PTBS-Symptome "verursacht", und die Wirkrichtung kann auch andersherum oder wechselseitig laufen. Zudem können sich Symptome gegenseitig überlagern: Angst etwa kann exekutive Funktionsprobleme sowohl nachahmen als auch verstärken, sodass ein "ADHS-typisches" Bild nicht automatisch ADHS bedeutet. Coaching-Takeaway: Diese Zahlen sind kein Werkzeug, um selbst eine Komorbiditäts-Vermutung zu äußern oder gar zu benennen — sie sind ein Grund, bei deutlichen Angst-, Stimmungs-, Sucht- oder Trauma-Anzeichen die Möglichkeit einer Komorbidität ernst zu nehmen und konsequent gemäß dem bestehenden Red-Flag-Protokoll an Fachpersonal weiterzuverweisen, statt alle Symptome pauschal auf ADHS zurückzuführen.$$),

(null, 'ADHS in Beziehung, Beruf und Führung: was die Forschung (nicht) zeigt', $$Forschung zu erwachsenem ADHS in Beziehungen, am Arbeitsplatz und in Führungspositionen kommt methodisch zu einem gemeinsamen Punkt: Die Befunde sind heterogen und stark kontextabhängig — funktionale Ergebnisse sind keine feste, automatische Folge der Diagnose. Konkret: Eine 2022 systematische Übersichtsarbeit zur Sozialkognition bei erwachsenem ADHS (16 Studien) fand Beeinträchtigungen nur in einigen, nicht in allen untersuchten Bereichen — "beeinflusst Beziehungen" ist etwas anderes als "verhindert liebevolle Beziehungen". Eine 2022 systematische Übersichtsarbeit zu unterstützenden Maßnahmen am Arbeitsplatz fand überraschend wenig kontextspezifische Interventionsforschung, obwohl das Thema viel diskutiert wird. Für Führung speziell gibt es keine Evidenzbasis, die die Frage "Können Menschen mit ADHS führen?" als Ja/Nein beantwortet — die eigentlich untersuchbare, coaching-relevante Frage ist eher, welche konkreten Führungsaufgaben (z. B. durchgehende Nachverfolgung, Delegation, bewusste Pausen/Entscheidungspunkte) von Externalisierung und struktureller Unterstützung profitieren. Coaching-Takeaway: Bei Beziehungs-, Job- oder Führungsthemen nicht pauschal von der ADHS-Diagnose auf Erfolg oder Misserfolg schließen, sondern konkret fragen, welche einzelne Funktion (Impulskontrolle? Organisation? Fokus-Ausdauer? Kommunikation?) in dieser spezifischen Situation tatsächlich die Hürde ist — und dort ansetzen statt bei der Diagnose als Ganzem.$$)

;
